# Generated by Django 4.1.7 on 2023-05-30 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_name', models.CharField(max_length=30, verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Сложность',
                'verbose_name_plural': 'Сложности',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('horse_img', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Фото')),
                ('breed', models.CharField(max_length=30, verbose_name='Порода')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Лошадь',
                'verbose_name_plural': 'Лошади',
                'ordering': ('horse_name',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=30, verbose_name='Название')),
                ('length', models.CharField(max_length=50, verbose_name='Протяжённость')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('complexity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.complexity', verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ('length',),
            },
        ),
        migrations.CreateModel(
            name='Types_of_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_training_name', models.CharField(max_length=30, verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'Вид тренировки',
                'verbose_name_plural': 'Виды тренировок',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=30, verbose_name='Название тренировки')),
                ('complexity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.complexity', verbose_name='Сложность')),
                ('types_training_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.types_of_training', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('sername', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('date_of_employment', models.DateTimeField(auto_now_add=True, verbose_name='Дата устройства')),
                ('types_training_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.types_of_training', verbose_name='Виды тренировок')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('service_img', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Фото')),
                ('service_sell', models.CharField(max_length=50, verbose_name='Цена')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.route', verbose_name='Описание')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.horse', verbose_name='Порода')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.trainer', verbose_name='Тренер')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.training', verbose_name='Тренировки')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('service_name',),
            },
        ),
        migrations.AddField(
            model_name='horse',
            name='sername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.trainer', verbose_name='Тренер'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.services', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
