# Generated by Django 4.1.6 on 2023-06-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='route',
        ),
    ]
