# Generated by Django 4.1.6 on 2023-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0002_horse_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.CharField(max_length=50, verbose_name='Протяжённость'),
        ),
    ]
