# Generated by Django 4.1.7 on 2024-06-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0002_remove_order_horse_remove_order_trainer_order_horse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trainer',
        ),
        migrations.AddField(
            model_name='order',
            name='horse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horse.horse', verbose_name='Лошадь'),
        ),
        migrations.AddField(
            model_name='order',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horse.trainer', verbose_name='Тренер'),
        ),
    ]
