# Generated by Django 4.1.6 on 2023-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0002_services_discount_services_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_sell',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
