# Generated by Django 4.1.6 on 2023-06-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0003_remove_order_horse_remove_order_trainer_order_horse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='birthday',
            field=models.DateField(auto_now_add=True, verbose_name='День рождения'),
        ),
    ]
