# Generated by Django 4.1.6 on 2023-06-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0003_alter_services_discount_alter_services_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='discount',
        ),
    ]
