# Generated by Django 4.1.6 on 2023-05-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0003_alter_route_description_alter_route_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='horse_name',
        ),
        migrations.AddField(
            model_name='services',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horse.horse', verbose_name='Порода'),
            preserve_default=False,
        ),
    ]
