# Generated by Django 4.1.7 on 2024-06-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0003_remove_order_horse_remove_order_trainer_order_horse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=150, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.TimeField(verbose_name='Начало времени')),
                ('datetime_end', models.TimeField(verbose_name='Конец времени')),
            ],
            options={
                'verbose_name': 'Рабочий график',
                'verbose_name_plural': 'Рабочие графики',
            },
        ),
        migrations.CreateModel(
            name='WorkDaysSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wds', to='horse.days', verbose_name='День')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.workschedule', verbose_name='График')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Расписание рабочих дней',
                'verbose_name_plural': 'Расписание рабочих дней',
            },
        ),
    ]
