# Generated by Django 4.1.6 on 2023-05-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0004_remove_services_horse_name_services_breed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
