# Generated by Django 4.1.6 on 2023-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0004_remove_services_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='sername',
        ),
        migrations.AddField(
            model_name='horse',
            name='trainer',
            field=models.ManyToManyField(to='horse.trainer', verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default=1, upload_to='%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='services',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='services',
            name='trainer',
        ),
        migrations.AddField(
            model_name='services',
            name='horse',
            field=models.ManyToManyField(to='horse.horse', verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='services',
            name='trainer',
            field=models.ManyToManyField(to='horse.trainer', verbose_name='Тренер'),
        ),
    ]
