# Generated by Django 4.1.6 on 2023-06-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0004_alter_horse_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='birthday',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_employment',
            field=models.DateField(verbose_name='Дата устройства'),
        ),
    ]
