# Generated by Django 4.1.6 on 2023-05-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0005_rename_services_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
