# Generated by Django 4.1.7 on 2024-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='elect',
            field=models.BooleanField(default=False, verbose_name='Избранный'),
        ),
    ]
