# Generated by Django 4.1.6 on 2023-06-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0007_alter_services_horse_alter_services_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
