# Generated by Django 4.1.7 on 2024-04-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0007_feedback_elect'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Не просмотрен'), ('access', 'Одобрен'), ('danger', 'Отказан')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
