# Generated by Django 4.1.7 on 2023-05-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0008_services_service_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='breed',
            new_name='horse',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='sername',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='training_name',
            new_name='training',
        ),
        migrations.RemoveField(
            model_name='services',
            name='route_name',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horse.route', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
