# Generated by Django 4.1.7 on 2024-04-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_horse_reg', '0004_profile_img'),
        ('horse', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_horse_reg.profile', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
