# Generated by Django 4.1.6 on 2023-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0009_alter_services_horse_alter_services_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='horse',
            field=models.ManyToManyField(blank=True, to='horse.horse', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='services',
            name='trainer',
            field=models.ManyToManyField(blank=True, to='horse.trainer', verbose_name='Тренер'),
        ),
    ]
