# Generated by Django 4.1.7 on 2024-04-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0009_feedback_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='img',
        ),
    ]
