# Generated by Django 4.1.7 on 2024-04-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0010_remove_feedback_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horse.trainer', verbose_name='Тренер'),
        ),
    ]
