# Generated by Django 4.1.6 on 2023-06-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0011_remove_order_horse_remove_order_trainer_order_horse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='horse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trainer',
        ),
        migrations.AddField(
            model_name='order',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_horse', to='horse.services', verbose_name='Лошадь'),
        ),
        migrations.AddField(
            model_name='order',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_trainer', to='horse.services', verbose_name='Тренер'),
        ),
    ]
