# Generated by Django 4.1.6 on 2023-06-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0012_remove_order_horse_remove_order_trainer_order_horse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horse.horse', verbose_name='Лошадь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horse.trainer', verbose_name='Тренер'),
        ),
    ]
