# Generated by Django 4.1.7 on 2024-05-09 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0012_alter_order_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время оказания услуги'),
            preserve_default=False,
        ),
    ]
