# Generated by Django 4.1.7 on 2024-05-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0013_services_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='time',
        ),
    ]
