# Generated by Django 4.1.7 on 2024-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0014_remove_services_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.IntegerField(default=1, max_length=1, verbose_name='Время оказания услуги'),
            preserve_default=False,
        ),
    ]
