# Generated by Django 4.1.7 on 2024-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0015_services_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.IntegerField(verbose_name='Время оказания услуги'),
        ),
    ]
