# Generated by Django 4.1.7 on 2024-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0016_alter_services_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.DurationField(verbose_name='Время оказания услуги'),
        ),
    ]
