# Generated by Django 4.1.7 on 2024-05-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0019_horse_is_busy_trainer_is_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='status',
        ),
    ]
