# Generated by Django 4.1.7 on 2024-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_horse_reg', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=1, upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
