# Generated by Django 4.1.7 on 2024-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_horse_reg', '0005_alter_profile_body_alter_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.TextField(verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
